# Configuración de PRODUCCIÓN - Máxima seguridad
spring:
  security:
    require-ssl: true # Forzar HTTPS en producción
  
  # Configuración de MongoDB más segura
  data:
    mongodb:
      # Usar variables de entorno para credenciales
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?retryWrites=true&w=majority&ssl=true&authSource=admin

server:
  port: ${SERVER_PORT:8086}
  # Configuración de seguridad del servidor
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false
  # Configuración de SSL/TLS
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

# Swagger deshabilitado en producción
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Solo endpoint de salud en producción
management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: info,metrics,prometheus,env,configprops,beans,shutdown
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: always
    metrics:
      enabled: false
    prometheus:
      enabled: false

# Configuración de logging segura
logging:
  level:
    root: WARN
    pe.edu.vallegrande: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ms-distribution.log
    max-size: 10MB
    max-history: 30

# Configuración de seguridad adicional
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000 # 24 horas
    rate-limit:
      requests-per-minute: 60 # Más restrictivo en producción
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://vallegrande.edu.pe,https://*.vallegrande.edu.pe,https://solid-halibut-pv749gjvjpw36469-4200.app.github.dev}
