# MONGO_DATABASE
spring:
  application:
    name: ${NOMBRE_MICROSERVICIO:structure-microservice}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME:sistemajass}:${MONGO_PASSWORD:ZC7O1Ok40SwkfEje}@sistemajass.jn6cpoz.mongodb.net/${MONGO_DATABASE:JASS_DIGITAL}?retryWrites=true&w=majority
  web:
    resources:
      cache:
        period: 0
  security:
    # Configuración de seguridad
    require-ssl: false # Solo para desarrollo local

server:
     port: 8086
     forward-headers-strategy: framework
     # Configuración de seguridad del servidor
     error:
       include-stacktrace: never
       include-message: never
       include-binding-errors: never
       include-exception: false

# Configuración CORS más restrictiva (se maneja en SecurityConfig)
# cors:
#      allowed-origins: "*"
#      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
#      allowed-headers: "*"
#      allow-credentials: true
#      max-age: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:false} # Solo habilitar en desarrollo
    urls:
      - url: /v3/api-docs
        name: API V1
  api-docs:
    path: /v3/api-docs
    enabled: ${SWAGGER_ENABLED:false} # Solo habilitar en desarrollo
  default-produces-media-type: application/json
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health # Solo endpoint de salud en producción
        exclude: info,metrics,prometheus,env,configprops,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:never} # Nunca mostrar detalles en producción
      show-components: always
    metrics:
      enabled: ${METRICS_ENABLED:false} # Solo en desarrollo
    prometheus:
      enabled: ${PROMETHEUS_ENABLED:false} # Solo en desarrollo

app:
  name: Water Distribution Microservice
  description: Microservicio para gestión de distribuciones en el servicio de agua
  version: 1.0.0s